cx/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'items.views.home', name='home'),
    # url(r'^cx/', include('cx.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Custom URLs
    url(r'^items/', include('items.urls')),
    url(r'^customauth/', include('customauth.urls')),
    url(r'^feedbacks/', include('reviews.feedback_urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

items/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('items.views',
	url(r'^$', 'explore'),
	url(r'^explore/$', 'explore'),
	url(r'^(?P<item_id>\d+)/$', 'view'), # items/25
	url(r'^(?P<item_id>\d+)/usage/add/$', 'add_usage_experience'), # items/25/used
	url(r'^add/', 'add'),
	url(r'^search/', 'search'),
	url(r'^moderate/', 'moderate_items'),
	url(r'^(?P<item_id>\d+)/approve/$', 'approve_item'),
	url(r'^(?P<item_id>\d+)/deactivate/$', 'deactivate_item'),
	url(r'^(?P<item_id>\d+)/edit/$', 'edit_item'),
	url(r'^(?P<item_id>\d+)/duplicates/$', 'get_possible_duplicates'),
	url(r'^(?P<item_id>\d+)/gallery/$', 'view_item_images'),
	url(r'^(?P<item_id>\d+)/gallery/add/$', 'add_item_image'),
	url(r'^prices/moderate/', 'moderate_prices'),
	url(r'^(?P<item_id>\d+)/prices/add/', 'add_price'),
	url(r'^prices/(?P<price_id>\d+)/approve/', 'approve_price'),
	url(r'^prices/(?P<price_id>\d+)/ignore/', 'ignore_price'),
	url(r'^(?P<item_id>\d+)/set_cover_image/', 'set_cover_image'),
	url(r'^latest/(?P<number>\d+)/$', 'get_latest'),
	url(r'^(?P<item_id>\d+)/stats/$', 'stats_page'),
	url(r'^(?P<item_id>\d+)/get_stats/$', 'get_stats'),
)

urlpatterns += patterns('reviews.views', 
	url(r'^(?P<item_id>\d+)/feedbacks/add/$', 'add_feedback'), # items/25/feedbacks/add
)

items/models.py
from django.db import models
from django.conf import settings
from django import forms
from django.db.models.signals import post_save, pre_delete
from items.receivers import save_item_sphinx, delete_item_sphinx
from items.item_utils import get_item_image_path
import Image
from django.utils import timezone
from contextlib import closing
import MySQLdb
from django.core.exceptions import ValidationError

# Create your models here.
class Category(models.Model):
	name = models.CharField(max_length=50, unique=True)

	def __unicode__(self):
		return self.name

class SpecificationType(models.Model):
	name = models.CharField(max_length=64, unique=True)
	description = models.CharField(max_length=256)
	categories = models.ManyToManyField(Category)

	def __unicode__(self):
		return self.name

class Specification(models.Model):
	name = models.CharField(max_length=64)
	description = models.CharField(max_length=256)
	spectype = models.ForeignKey(SpecificationType)

	class Meta:
		unique_together = ('name', 'spectype')

	def __unicode__(self):
		return self.name

class ItemPossibleDuplicates(models.Model):
	str_list = models.CharField(max_length=512)
	number = models.PositiveSmallIntegerField()

	def __unicode__(self):
		return self.str_list

class Item(models.Model):
	name = models.CharField(max_length=200, unique=True)
	date_created = models.DateTimeField('date created')
	created_by = models.ForeignKey(settings.AUTH_USER_MODEL)
	category = models.ForeignKey(Category)
	cover_image = models.ForeignKey('ItemImage', related_name="cover_image", null=True, blank=True)
	is_active = models.BooleanField(default=True, blank=True)
	is_approved = models.BooleanField(default=False, blank=True)
	latest_feedback = models.ForeignKey('reviews.Feedback', related_name="items_latest_set", null=True, blank=True)
	views_count = models.PositiveIntegerField(default=0)
	pros_count = models.PositiveIntegerField(default=0)
	cons_count = models.PositiveIntegerField(default=0)
	possible_duplicates = models.OneToOneField(ItemPossibleDuplicates, null=True, blank=True)
	specifications = models.ManyToManyField(Specification)
	avg_rating = models.DecimalField(max_digits=3, decimal_places=2, default=0)
	reviewers_count = models.PositiveIntegerField(default=0)

	class Meta:
		permissions = (
			("moderate_items", "Can access views related to item moderation"), 
		)

	def get_similar_item_ids(self, name=None):
		if not name:
			name = self.name

		connection = MySQLdb.connect(host=settings.SPHINXQL_HOST, port=settings.SPHINXQL_PORT)
		with closing(connection.cursor()) as cursor:
			cursor.execute("select * from items_item where match('@name %s')" % str(name)) # is it safe?
			ids = [row[0] for row in cursor.fetchall()] # is it efficient?	
		connection.close()
		return ids

	def __unicode__(self):
		return 'name:' + self.name + ',' + 'category:' + self.category.name


post_save.connect(save_item_sphinx, sender=Item)
pre_delete.connect(delete_item_sphinx, sender=Item)

class ItemAddForm(forms.ModelForm):
	class Meta:
		model = Item
		fields = ('name', 'category')

class ItemApprovalHistory(models.Model):
	item = models.ForeignKey(Item)
	moderator = models.ForeignKey(settings.AUTH_USER_MODEL)
	date_approved = models.DateTimeField()

class ItemDeactivationReason(models.Model):
	reason = models.CharField(max_length=200, unique=True)

	def __unicode__(self):
		return self.reason

class ItemDeactivationHistory(models.Model):
	item = models.ForeignKey(Item)
	moderator = models.ForeignKey(settings.AUTH_USER_MODEL)
	date_deactivated = models.DateTimeField()
	reason = models.ForeignKey(ItemDeactivationReason)
	duplicate_of = models.ForeignKey(Item, related_name='duplicate_of', null=True, blank=True)

class ItemDeactivationForm(forms.ModelForm):
	class Meta:
		model = ItemDeactivationHistory
		fields = ('reason', 'duplicate_of')

class ItemEditReason(models.Model):
	reason = models.CharField(max_length=200, unique=True)

	def __unicode__(self):
		return self.reason

class ItemEditHistory(models.Model):
	item = models.ForeignKey(Item)
	moderator = models.ForeignKey(settings.AUTH_USER_MODEL)
	date_edited = models.DateTimeField()
	reason = models.ForeignKey(ItemEditReason)
	other_reason = models.CharField(max_length=200, null=True)
	old_value = models.CharField(max_length=200)

class ItemEditForm(forms.Form):
	# Item
	name = forms.CharField(max_length=200)
	category = forms.ModelChoiceField(queryset=Category.objects.all(), widget=forms.Select, empty_label=None)
	# Reason
	reason = forms.ModelChoiceField(queryset=ItemEditReason.objects.all(), widget=forms.RadioSelect, empty_label=None)
	other_reason = forms.CharField(max_length=200, required=False)

	"""
	https://docs.djangoproject.com/en/dev/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other
	"""
	def clean(self):
		cleaned_data = super(ItemEditForm, self).clean()
		reason = cleaned_data.get('reason')
		other_reason = cleaned_data.get('other_reason', None)
		
		if reason and reason.reason == 'Other' and not other_reason:
			msg = u"Other reason must be specified"
			self._errors["other_reason"] = self.error_class([msg])
			del cleaned_data['other_reason']

		return cleaned_data

class ItemUsageDurationType(models.Model):
	string = models.CharField(max_length=255)
	value = models.PositiveSmallIntegerField()

	class Meta:
		unique_together = ('string', 'value')

	def __unicode__(self):
		return self.string

class ItemUsageRatingType(models.Model):
	string = models.CharField(max_length=64)
	value = models.PositiveSmallIntegerField()

	class Meta:
		unique_together = ('string', 'value')
		ordering = ('value',)

	def __unicode__(self):
		return self.string

class ItemUsageExperience(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL)
	item = models.ForeignKey(Item)
	duration = models.ForeignKey(ItemUsageDurationType, default=1)
	rating = models.ForeignKey(ItemUsageRatingType, default=4)
	date_verified = models.DateTimeField('date when user verified usage')

class ItemUsageForm(forms.ModelForm):
	class Meta:
		model = ItemUsageExperience
		fields = ('duration', 'rating',)

class ItemImage(models.Model):
	item = models.ForeignKey(Item)
	image = models.ImageField(upload_to=get_item_image_path)
	image_mini_thumb = models.ImageField(upload_to="gallery_thumb_buggy_imgs", blank=True)
	image_cover_thumb = models.ImageField(upload_to="gallery_thumb_buggy_imgs", blank=True, null=True)
	image_gallery_thumb = models.ImageField(upload_to="gallery_thumb_buggy_imgs", 
		blank=True)
	uploaded_by = models.ForeignKey(settings.AUTH_USER_MODEL)
	date_uploaded = models.DateTimeField()

	class Meta:
		unique_together = ('image', 'image')

	def save(self, request=None, *args, **kwargs):
		super(ItemImage, self).save(*args, **kwargs)
		image_full_path = settings.MEDIA_ROOT + self.image.name
		orignal_image = Image.open(image_full_path)
		width, height = orignal_image.size
		
		# let's -D-RY some images :)
		
		# creating mini_thumb
		new_width = 70
		path = 'itemimage_mini_thumbs/' + self.image.name.split('/')[1]
		if width > new_width:
			new_height = int(height * new_width / width)
			mini_thumb = orignal_image.resize((new_width, new_height), Image.ANTIALIAS)
			mini_thumb.save(settings.MEDIA_ROOT + path, "JPEG")
		else:
			path = image_full_path
		self.image_mini_thumb = path
		
		# creating gallery_thumb
		new_width = 200
		path = 'itemimage_gallery_thumbs/' + self.image.name.split('/')[1]
		if width > new_width:
			new_height = int(height * new_width / width)
			gallery_thumb = orignal_image.resize((new_width, new_height), Image.ANTIALIAS)
			gallery_thumb.save(settings.MEDIA_ROOT + path, "JPEG")			
		else:
			path = image_full_path
		self.image_gallery_thumb = path
		
		# creating cover_thumb
		new_width = 940
		if width > new_width:
			new_height = int(height * new_width / width)
			cover_thumb = orignal_image.resize((new_width, new_height), Image.ANTIALIAS)
			path = 'itemimage_cover_thumbs/' + self.image.name.split('/')[1]
			cover_thumb.save(settings.MEDIA_ROOT + path, "JPEG")
			self.image_cover_thumb = path
		
		super(ItemImage, self).save(*args, **kwargs)

class ItemImageUploadForm(forms.Form):
	image = forms.ImageField()

	def clean_image_size(self):
		image = self.cleaned_data.get('image', False)
		if image:
			if image._size > 2097152:
				raise ValidationError("Image is too large")
			return image
		else:
			raise ValidationError("Couldn't read image file")

class Price(models.Model):
	item = models.ForeignKey(Item)
	value = models.DecimalField(max_digits=10, decimal_places=2)
	source_url = models.URLField()
	date_added = models.DateTimeField()
	added_by = models.ForeignKey(settings.AUTH_USER_MODEL)
	is_active = models.BooleanField(default=True)
	is_approved = models.BooleanField(default=False)
	resolved_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="resolver", null=True)

class PriceAddForm(forms.ModelForm):
	class Meta:
		model = Price
		fields = ('value', 'source_url',)

templates/items/add.html
{% extends "base.html" %}
{% block content %}
	<form method="post" action='{% url "items.views.add" %}'>
		{% csrf_token %}
		{{ form.non_field_errors }}
	    <div class="fieldWrapper">
	        {{ form.name.errors }}
	        <label for="id_name">Name:</label>
	        {{ form.name }}
	        <!-- similar items -->
		    <div id="similar_items" data-similars='{"input_name": "name", "url": "/items/search/", "ich_id": "similar_item"}' style="display:none;">
				<h5>Make sure you are not repeating these:</h5>
				<ul id="results_list">
				</ul>
			</div>
	    </div>
	    <div class="fieldWrapper">
	        {{ form.category.errors }}
	        <label for="id_category">Category:</label>
	        {{ form.category }}
	    </div>
		<input type="submit" value="add" />
	</form>
	<script type="text/javascript">
		$(document).ready(function() {
			siteNameSpace.exec("item_add");
		})
	</script>
	<script type="text/html" id="similar_item">
		<li id="similar_item">
			{% verbatim %}
			<a href="/items/{{ id }}">{{ name }}</a>
			{% endverbatim %}
		</li>
	</script>
{% endblock %}

templates/items/categories.html
<ul class="nav nav-list" id="categories">
	<li id="all"><a href="/items/explore/">All</a></li>
	<li class="nav-header">Electronics</li>
	<li id="smartphones"><a href="/items/explore/?category=smartphones">Smartphones</a></li>
	<li id=tablets><a href="/items/explore/?category=tablets">Tablets</a></li>
	<li id="laptops"><a href="/items/explore/?category=laptops">Laptops</a></li>
	<li id="transformers"><a href="/items/explore/?category=transformers">Transformers</a></li>
</ul>

templates/items/explore.html
{% extends "base.html" %}
{% block content %}
	<div class="row">
		<div class="span2" id="left_sidebar">
			{% include "items/categories.html" %}
		</div>
		<div class="span8">
			{% if latest_item_list %}
				<ul id="items">
					{% for item in latest_item_list %}
						<li id="item">
							<div id="item">
								<div id="item_info">
									<div id="item_name">
										<a href="/items/{{ item.id }}" id="item_name">{{ item.name }}</a>
									</div>
									<div id="item_stats">
										<span id="pros_count">{{ item.pros_count }}</span><span id="cons_count">{{ item.cons_count }}</span>
										<span id="views_count">{{ item.views_count }} views</span>
									</div>
								</div>
								{% if item.cover_image %}
								<div id="image_thumbnail">
									<a href=""><img src="{{ item.cover_image.image_mini_thumb.url }}"></a>
								</div>
								{% endif %}
							</div>
							{% if item.latest_feedback %}
							<div class="latest_feedback" id={% if item.latest_feedback.is_positive %}"pro"{% else %}"con"{% endif %}>
								<div id="latest_feedback_body">
									<!-- <span>latest: </span> --><a id="latest_feedback" href="/items/{{item.id}}/#{{item.latest_feedback.id}}">“{{ item.latest_feedback.body }}”</a>
								</div>
								<div id="feedback_stats">

								</div>
							</div>
							{% endif %}
						</li>
					{% endfor %}
				</ul>
			{% else %}
				<p>No items are available</p>
			{% endif %}
		</div>
		<div class="span2"></div>
	</div>
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}/css/explore.css">
<script type="text/javascript">
	$(document).ready(function () {
		$('li.active').removeClass('active');
		$('li#{{ category_name }}').addClass('active');
	});
</script>
{% endblock %}

templates/items/not_used-modal.html
<!-- Modal -->
<div id="not_used-modal" class="modal hide fade">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<center><h3>Verification</h3></center>
	</div>
	<div class="modal-body">
		<h4 class="text-warning">In order to perform actions you need to assure that you used this item</h4>
		<form id="usage_form" method="post" action="/items/{{ item.id }}/usage/add/">
			{% csrf_token %}
			I used <span style="font-style: italic;">{{ item.name }}</span> for {{ usage_form.duration }} and rate it as {{ usage_form.rating }}
			<button type="submit" class="btn" style="margin: -10px 0 0 10px;">Submit <i class="icon-ok-sign"></i></button>
		</form>
	</div>
	<div class="modal-footer">
		<a href="#" class="btn" data-dismiss="modal">Cancel</a>
	</div>
</div>

templates/items/stats.html
{% extends "base.html" %}
{% block content %}
<div class="row">
	<div class="span12">
		<div class="item" id="{{ item.id }}">
			Stats for <a href="/items/{{ item.id }}/">{{ item.name }}</a>
		</div>
		<div id="ratings_table" class="chart"></div>
		<div id="ages_table" class="chart"></div>
		<div id="countries_table" class="chart"></div>
		<div id="genders_table" class="chart"></div>
		<div id="prices_table" class="chart"></div>
	</div>
</div>
<script type="text/javascript">
	$(document).ready(function () {
		siteNameSpace.exec('stats', {page: 'item'});
	});
</script>
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}/css/stats.css">
{% endblock %}

templates/items/usage-form.html
<form id="usage_form" method="post" action="/items/{{ item.id }}/usage/add/">
	{% csrf_token %}
	<span id="usage_sentence">I used this {{ item.category }} for {{ usage_form.duration }} and rate it as {{ usage_form.rating }}</span>
	<button type="submit" class="btn" id="usage_submit">Submit <i class="icon-ok-sign"></i></button>
</form>

templates/items/usage-form_draft.html
<form id="usage_form" method="post" action="/items/used/">
	{% csrf_token %}
	<span id="usage_sentence">I used this {{ item.category }} for 
		<select name="duration" id="id_duration">
			<option value="1" selected="selected">less than one month</option>
			<option value="2">few monthes</option>
			<option value="3">more than a year</option>
		</select>
		 and rate it as 
		<select name="rating" id="id_rating">
			<option value="1">terrible</option>
			<option value="2">bad</option>
			<option value="4" selected="selected">good</option>
			<option value="5">excellent</option>
		</select>
		.</span>
	<input type="submit" class="btn" />
</form>

templates/items/view.html
{% extends "base.html" %}
{% load humanize %}
{% block content %}
	<div class="row">
		<div class="span12">
			<div id="item_wrapper" {% if item.cover_image %} style="background-image: url({{ item.cover_image.image_cover_thumb.url }});min-height: {{ item.cover_image.image_cover_thumb.height }}px; position: relative;" {% endif %}>
				<div id="item" item-id="{{ item.id }}" {% if item.cover_image %} style="position: absolute; bottom: 0; left: 0;" {% endif %}>
					<div id="item_info">
						<div id="item_name">
							{{ item.name }}
							{% if experience %}
								<i class="icon-ok-sign icon-white" id="icon_used"></i>
							{% endif %}
						</div>

						<span id="item_rating">{{ item.avg_rating|floatformat }}/5</span>
						
						<div id="reviews_info">
							<div id="proscons_count">
								<span id="pros_count">{{ item.pros_count }}</span><span id="cons_count">{{ item.cons_count }}</span>
							</div>

							<div id="reviewers_count">
								<span>{{ item.reviewers_count }}</span> reviewer{{ item.reviewers_count|pluralize }}
							</div>
						</div>
					</div>
					<div id="user_experience">
						{% if experience %}
							<a href="/item/{{ item.id }}/usage/edit/" id="user_rating">You gave {{ experience.rating.value }}/5</a>
						{% else %}
							<a class="btn btn-mini" id="used"><i class="icon-ok"></i> I used this {{ item.category }}</a>
							{% include "items/not_used-modal.html" %}
						{% endif %}
					</div>
					<div id="bottom" {% if item.cover_image %} style="width: 918px;" {% endif %}>
						<div id="prices">
							{% if latest_price %}
								{{ latest_price.value|floatformat }}$ <span id="price_date"> - {{ latest_price.date_added|naturaltime }}</span>
							{% endif %}
						</div>

						{% if item.specifications %}
							<div id="specifications">
								{% for specification in item.specifications.all %}
									<a href="/items/specifications/search/" data-toggle="tooltip" title="{{ specification.spectype }}">{{ specification.name }}</a>
								{% endfor %}
							</div>
						{% endif %}
					</div>
				</div>
			</div>
		</div>
	</div>
	{% if user.is_authenticated %}
		{% include "reviews/feedbacks/suggest_edit-modal.html" %}
	{% endif %}

	<div class="row">
		<div class="span12" id="proscons">
			<div id="item_actions">
				<button class="btn btn-small" id="hide_actions"><i class="icon-eye-close"></i> Hide actions</button>
				{% if latest_price %}
					<a href="/items/{{ item.id }}/prices/add/" id="add_price">Suggest new price</a>
				{% else %}
					<a href="/items/{{ item.id }}/prices/add/" id="add_price">Suggest price</a>
				{% endif %}
				<a href="/items/{{ item.id }}/prices/history/" id="add_price">Price history</a>
				<a href="/items/{{ item.id }}/gallery/"><i class="icon-camera"></i> Gallery</a>
				<a href="/items/{{ item.id }}/stats/"><i class="icon-align-right"></i> Stats</a>
			</div>
			<div id="proscons_wrapper">
				<div class="feedback_column" id="pros">
					<div id="pros_label" class="column_label">
					</div>
					<ul id="feedbacks">
						{% for feedback in feedbacks %}
							{% if feedback.is_positive %}
								{% include "reviews/feedbacks/feedback-li.html" %}
							{% endif %}
						{% endfor %}
					</ul>
					{% if user.is_authenticated and experience %}
						{% include "reviews/feedbacks/add.html" with is_positive=1 %}
					{% else %}
						<a href="javascript:void(0);" id="add_feedback">Add feedback</a>
						{% include "reviews/feedbacks/add.html" with is_positive=1 hidden=True%}
					{% endif %}
				</div>
				<div class="feedback_column" id="cons">
					<div id="cons_label" class="column_label">
						
					</div>
					<ul id="feedbacks">
						{% for feedback in feedbacks %}
							{% if not feedback.is_positive %}
								{% include "reviews/feedbacks/feedback-li.html" %}
							{% endif %}
						{% endfor %}
					</ul>
					{% if user.is_authenticated and experience %}
						{% include "reviews/feedbacks/add.html" with is_positive=0 %}
					{% else %}
						<a href="javascript:void(0);" id="add_feedback">Add feedback</a>
						{% include "reviews/feedbacks/add.html" with is_positive=0 hidden=True%}
					{% endif %}
				</div>
			</div>
		</div>
	</div>
	<!-- ICanHaz templates -->
	<script type="text/html" id="feedback">
		<li class="feedback" id='{% verbatim %}{{ id }}{% endverbatim %}'>
			<div id="score">0</div>
			<div id="feedback_body">
				{% verbatim %}
				<div id="body">{{ body }}</div>
				{% endverbatim %}
			</div>
			<div id="actions">
				<button class="vote btn btn-mini" type-id="1" weight="1">Agree</button>
				<button class="vote btn btn-mini" type-id="2" weight="-1">Disagree</button>
				<a href="#" id="suggest_edit">Suggest edits</a>
			</div>
			<div id="ss">
				<span id='agrees_count'>0</span> Agrees
				<span id='disagrees_count'>0</span> Disagrees
				Priorities: 
				1-<span class="priority" id="1">0</span>
				2-<span class="priority" id="2">0</span>
				3-<span class="priority" id="3">0</span>
				<a id="details_link" href="/feedbacks/{{ feedback.id }}/details">Details(<span id="count">0</span>)</a>
			</div>
		</li>
	</script>
	<script type="text/html" id="similar_feedback">
		<li id="similar_feedback">
			{% verbatim %}
			<a href="#{{ id }}">{{ body }}</a>
			{% endverbatim %}
		</li>
	</script>
	<script type="text/html" id="set_priority">
		{% verbatim %}
		<button href="javascript:void(0);" class="set_priority btn btn-mini">#{{ value }}</button>
		{% endverbatim %}
	</script>
	{% verbatim %}
	<script type="text/html" id="suggest_edit_form">
		<div id="orig_feedback">{{ feedback_body }}</div>
		<form action="/feedbacks/{{ feedback_id }}/suggest_edit/" method="post" id="suggest_edit">
			<div class="form-inline">
				<input type="text" name="suggested_value" value="{{ feedback_body }}" autofocus>
				<input type="submit" class="btn btn-info" value="Submit for review">
			</div>	
		</form>
	</script>
	{% endverbatim %}
	<script type="text/html" id="user_rating">
		{% verbatim %}
		<a href="/item/{{ item_id }}/usage/edit/" id="user_rating">You gave {{ user_rating }}/5</a>
		{% endverbatim %}
	</script>
	<!-- JavaScript -->
	<script type="text/javascript">
		$(document).ready(function() {
			{% if user.is_authenticated %}
				{% if experience %}
					siteNameSpace.exec('review', { is_authenticated: true, is_used: true });
				{% else %}
					siteNameSpace.exec('review', { is_authenticated: true, is_used: false });
				{% endif %}
			{% else %}
				siteNameSpace.exec('review');	// default configuration is set to {is_authenticated: false}, so guest() will fire
			{% endif %}
		});
	</script>
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}/css/review.css">
{% endblock %}